// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P04Sklep.API.Data;

#nullable disable

namespace P04Sklep.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230227101602_MaterialCategoryIdAddNullable")]
    partial class MaterialCategoryIdAddNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P05Sklep.Shared.MaterialCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MaterialCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Granite",
                            Url = "Granite"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Plastic",
                            Url = "Plastic"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Steel",
                            Url = "Steel"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fresh",
                            Url = "Fresh"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fresh",
                            Url = "Fresh"
                        });
                });

            modelBuilder.Entity("P05Sklep.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaterialCategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("Premium")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "ivory",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImageUrl = "https://loremflickr.com/320/240?lock=201469123",
                            MaterialCategoryId = 4,
                            Premium = true,
                            Title = "Fantastic Soft Table"
                        },
                        new
                        {
                            Id = 2,
                            Color = "olive",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1980142465",
                            MaterialCategoryId = 1,
                            Premium = true,
                            Title = "Licensed Granite Shoes"
                        },
                        new
                        {
                            Id = 3,
                            Color = "mint green",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImageUrl = "https://loremflickr.com/320/240?lock=2092027196",
                            MaterialCategoryId = 2,
                            Premium = true,
                            Title = "Small Plastic Shirt"
                        },
                        new
                        {
                            Id = 4,
                            Color = "azure",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1716843403",
                            MaterialCategoryId = 2,
                            Premium = false,
                            Title = "Generic Soft Sausages"
                        },
                        new
                        {
                            Id = 5,
                            Color = "mint green",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1472280000",
                            MaterialCategoryId = 4,
                            Premium = true,
                            Title = "Gorgeous Soft Salad"
                        },
                        new
                        {
                            Id = 6,
                            Color = "ivory",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImageUrl = "https://loremflickr.com/320/240?lock=2013538639",
                            MaterialCategoryId = 3,
                            Premium = true,
                            Title = "Small Granite Hat"
                        },
                        new
                        {
                            Id = 7,
                            Color = "silver",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImageUrl = "https://loremflickr.com/320/240?lock=824828375",
                            MaterialCategoryId = 1,
                            Premium = false,
                            Title = "Licensed Cotton Pants"
                        },
                        new
                        {
                            Id = 8,
                            Color = "grey",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImageUrl = "https://loremflickr.com/320/240?lock=680241028",
                            MaterialCategoryId = 2,
                            Premium = false,
                            Title = "Ergonomic Granite Bacon"
                        },
                        new
                        {
                            Id = 9,
                            Color = "teal",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImageUrl = "https://loremflickr.com/320/240?lock=2002758",
                            MaterialCategoryId = 4,
                            Premium = false,
                            Title = "Handcrafted Metal Pants"
                        },
                        new
                        {
                            Id = 10,
                            Color = "gold",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImageUrl = "https://loremflickr.com/320/240?lock=600673691",
                            MaterialCategoryId = 1,
                            Premium = true,
                            Title = "Licensed Steel Tuna"
                        },
                        new
                        {
                            Id = 11,
                            Color = "green",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImageUrl = "https://loremflickr.com/320/240?lock=262093381",
                            MaterialCategoryId = 1,
                            Premium = false,
                            Title = "Ergonomic Fresh Towels"
                        },
                        new
                        {
                            Id = 12,
                            Color = "fuchsia",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImageUrl = "https://loremflickr.com/320/240?lock=284027703",
                            MaterialCategoryId = 2,
                            Premium = false,
                            Title = "Awesome Plastic Bike"
                        },
                        new
                        {
                            Id = 13,
                            Color = "gold",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1000474489",
                            MaterialCategoryId = 5,
                            Premium = true,
                            Title = "Incredible Fresh Cheese"
                        },
                        new
                        {
                            Id = 14,
                            Color = "teal",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1650116988",
                            MaterialCategoryId = 1,
                            Premium = false,
                            Title = "Ergonomic Metal Bike"
                        },
                        new
                        {
                            Id = 15,
                            Color = "plum",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1024280969",
                            MaterialCategoryId = 2,
                            Premium = true,
                            Title = "Unbranded Cotton Chips"
                        },
                        new
                        {
                            Id = 16,
                            Color = "green",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImageUrl = "https://loremflickr.com/320/240?lock=592933680",
                            MaterialCategoryId = 4,
                            Premium = false,
                            Title = "Incredible Granite Ball"
                        },
                        new
                        {
                            Id = 17,
                            Color = "salmon",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImageUrl = "https://loremflickr.com/320/240?lock=503650170",
                            MaterialCategoryId = 4,
                            Premium = false,
                            Title = "Practical Cotton Bacon"
                        },
                        new
                        {
                            Id = 18,
                            Color = "ivory",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1919107616",
                            MaterialCategoryId = 4,
                            Premium = false,
                            Title = "Rustic Concrete Chair"
                        },
                        new
                        {
                            Id = 19,
                            Color = "teal",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1996083900",
                            MaterialCategoryId = 4,
                            Premium = true,
                            Title = "Unbranded Concrete Chips"
                        },
                        new
                        {
                            Id = 20,
                            Color = "ivory",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImageUrl = "https://loremflickr.com/320/240?lock=2135157739",
                            MaterialCategoryId = 4,
                            Premium = false,
                            Title = "Generic Steel Keyboard"
                        },
                        new
                        {
                            Id = 21,
                            Color = "mint green",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImageUrl = "https://loremflickr.com/320/240?lock=396869378",
                            MaterialCategoryId = 3,
                            Premium = true,
                            Title = "Awesome Wooden Fish"
                        },
                        new
                        {
                            Id = 22,
                            Color = "purple",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1441451149",
                            MaterialCategoryId = 2,
                            Premium = false,
                            Title = "Intelligent Granite Towels"
                        },
                        new
                        {
                            Id = 23,
                            Color = "black",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImageUrl = "https://loremflickr.com/320/240?lock=204197834",
                            MaterialCategoryId = 3,
                            Premium = false,
                            Title = "Rustic Cotton Table"
                        },
                        new
                        {
                            Id = 24,
                            Color = "purple",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImageUrl = "https://loremflickr.com/320/240?lock=929421207",
                            MaterialCategoryId = 5,
                            Premium = true,
                            Title = "Handcrafted Steel Chips"
                        },
                        new
                        {
                            Id = 25,
                            Color = "cyan",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImageUrl = "https://loremflickr.com/320/240?lock=284845873",
                            MaterialCategoryId = 1,
                            Premium = false,
                            Title = "Fantastic Granite Fish"
                        },
                        new
                        {
                            Id = 26,
                            Color = "gold",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImageUrl = "https://loremflickr.com/320/240?lock=292858009",
                            MaterialCategoryId = 1,
                            Premium = true,
                            Title = "Licensed Fresh Chicken"
                        },
                        new
                        {
                            Id = 27,
                            Color = "purple",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImageUrl = "https://loremflickr.com/320/240?lock=946058532",
                            MaterialCategoryId = 4,
                            Premium = false,
                            Title = "Intelligent Wooden Towels"
                        },
                        new
                        {
                            Id = 28,
                            Color = "salmon",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1151742041",
                            MaterialCategoryId = 5,
                            Premium = false,
                            Title = "Gorgeous Rubber Pants"
                        },
                        new
                        {
                            Id = 29,
                            Color = "fuchsia",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImageUrl = "https://loremflickr.com/320/240?lock=846132012",
                            MaterialCategoryId = 5,
                            Premium = false,
                            Title = "Unbranded Fresh Sausages"
                        },
                        new
                        {
                            Id = 30,
                            Color = "blue",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1676100833",
                            MaterialCategoryId = 5,
                            Premium = false,
                            Title = "Generic Plastic Towels"
                        });
                });

            modelBuilder.Entity("P05Sklep.Shared.ProductAdjective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductAdjectives");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gorgeous"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Incredible"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ergonomic"
                        });
                });

            modelBuilder.Entity("P05Sklep.Shared.Product_ProductAdjective", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductAdjectiveId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("ProductId", "ProductAdjectiveId");

                    b.HasIndex("ProductAdjectiveId");

                    b.ToTable("Product_ProductAdjectives");

                    b.HasData(
                        new
                        {
                            ProductId = 6,
                            ProductAdjectiveId = 1,
                            Price = 53m
                        },
                        new
                        {
                            ProductId = 3,
                            ProductAdjectiveId = 3,
                            Price = 57m
                        },
                        new
                        {
                            ProductId = 14,
                            ProductAdjectiveId = 2,
                            Price = 76m
                        },
                        new
                        {
                            ProductId = 26,
                            ProductAdjectiveId = 3,
                            Price = 143m
                        },
                        new
                        {
                            ProductId = 2,
                            ProductAdjectiveId = 2,
                            Price = 734m
                        },
                        new
                        {
                            ProductId = 3,
                            ProductAdjectiveId = 2,
                            Price = 385m
                        },
                        new
                        {
                            ProductId = 24,
                            ProductAdjectiveId = 1,
                            Price = 712m
                        },
                        new
                        {
                            ProductId = 20,
                            ProductAdjectiveId = 1,
                            Price = 961m
                        },
                        new
                        {
                            ProductId = 8,
                            ProductAdjectiveId = 3,
                            Price = 58m
                        },
                        new
                        {
                            ProductId = 17,
                            ProductAdjectiveId = 2,
                            Price = 589m
                        },
                        new
                        {
                            ProductId = 8,
                            ProductAdjectiveId = 2,
                            Price = 625m
                        },
                        new
                        {
                            ProductId = 13,
                            ProductAdjectiveId = 2,
                            Price = 708m
                        },
                        new
                        {
                            ProductId = 15,
                            ProductAdjectiveId = 3,
                            Price = 27m
                        },
                        new
                        {
                            ProductId = 11,
                            ProductAdjectiveId = 1,
                            Price = 643m
                        },
                        new
                        {
                            ProductId = 9,
                            ProductAdjectiveId = 3,
                            Price = 935m
                        },
                        new
                        {
                            ProductId = 4,
                            ProductAdjectiveId = 2,
                            Price = 802m
                        },
                        new
                        {
                            ProductId = 16,
                            ProductAdjectiveId = 1,
                            Price = 949m
                        },
                        new
                        {
                            ProductId = 8,
                            ProductAdjectiveId = 1,
                            Price = 144m
                        },
                        new
                        {
                            ProductId = 11,
                            ProductAdjectiveId = 3,
                            Price = 223m
                        },
                        new
                        {
                            ProductId = 30,
                            ProductAdjectiveId = 3,
                            Price = 872m
                        },
                        new
                        {
                            ProductId = 6,
                            ProductAdjectiveId = 3,
                            Price = 140m
                        },
                        new
                        {
                            ProductId = 12,
                            ProductAdjectiveId = 1,
                            Price = 380m
                        },
                        new
                        {
                            ProductId = 18,
                            ProductAdjectiveId = 3,
                            Price = 879m
                        },
                        new
                        {
                            ProductId = 5,
                            ProductAdjectiveId = 1,
                            Price = 911m
                        },
                        new
                        {
                            ProductId = 3,
                            ProductAdjectiveId = 1,
                            Price = 154m
                        },
                        new
                        {
                            ProductId = 15,
                            ProductAdjectiveId = 2,
                            Price = 211m
                        },
                        new
                        {
                            ProductId = 30,
                            ProductAdjectiveId = 2,
                            Price = 507m
                        },
                        new
                        {
                            ProductId = 18,
                            ProductAdjectiveId = 2,
                            Price = 879m
                        },
                        new
                        {
                            ProductId = 9,
                            ProductAdjectiveId = 1,
                            Price = 293m
                        },
                        new
                        {
                            ProductId = 22,
                            ProductAdjectiveId = 3,
                            Price = 413m
                        },
                        new
                        {
                            ProductId = 16,
                            ProductAdjectiveId = 2,
                            Price = 646m
                        },
                        new
                        {
                            ProductId = 2,
                            ProductAdjectiveId = 1,
                            Price = 177m
                        },
                        new
                        {
                            ProductId = 1,
                            ProductAdjectiveId = 1,
                            Price = 638m
                        },
                        new
                        {
                            ProductId = 11,
                            ProductAdjectiveId = 2,
                            Price = 447m
                        },
                        new
                        {
                            ProductId = 5,
                            ProductAdjectiveId = 3,
                            Price = 609m
                        },
                        new
                        {
                            ProductId = 26,
                            ProductAdjectiveId = 1,
                            Price = 960m
                        },
                        new
                        {
                            ProductId = 26,
                            ProductAdjectiveId = 2,
                            Price = 763m
                        },
                        new
                        {
                            ProductId = 29,
                            ProductAdjectiveId = 3,
                            Price = 994m
                        },
                        new
                        {
                            ProductId = 14,
                            ProductAdjectiveId = 3,
                            Price = 896m
                        },
                        new
                        {
                            ProductId = 25,
                            ProductAdjectiveId = 1,
                            Price = 771m
                        },
                        new
                        {
                            ProductId = 13,
                            ProductAdjectiveId = 3,
                            Price = 983m
                        });
                });

            modelBuilder.Entity("P05Sklep.Shared.Product", b =>
                {
                    b.HasOne("P05Sklep.Shared.MaterialCategory", "MaterialCategory")
                        .WithMany()
                        .HasForeignKey("MaterialCategoryId");

                    b.Navigation("MaterialCategory");
                });

            modelBuilder.Entity("P05Sklep.Shared.Product_ProductAdjective", b =>
                {
                    b.HasOne("P05Sklep.Shared.ProductAdjective", "ProductAdjective")
                        .WithMany()
                        .HasForeignKey("ProductAdjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P05Sklep.Shared.Product", "Product")
                        .WithMany("Product_ProductAdjectives")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductAdjective");
                });

            modelBuilder.Entity("P05Sklep.Shared.Product", b =>
                {
                    b.Navigation("Product_ProductAdjectives");
                });
#pragma warning restore 612, 618
        }
    }
}
