// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P04Sklep.API.Data;

#nullable disable

namespace P04Sklep.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230208091149_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P05Sklep.Shared.MaterialCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MaterialCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Granite",
                            Url = "Granite"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fresh",
                            Url = "Fresh"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rubber",
                            Url = "Rubber"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Soft",
                            Url = "Soft"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Frozen",
                            Url = "Frozen"
                        });
                });

            modelBuilder.Entity("P05Sklep.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaterialCategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("Premium")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "lime",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1819115489",
                            MaterialCategoryId = 5,
                            Premium = false,
                            Title = "Incredible Granite Ball"
                        },
                        new
                        {
                            Id = 2,
                            Color = "ivory",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ImageUrl = "https://loremflickr.com/320/240?lock=304157057",
                            MaterialCategoryId = 5,
                            Premium = false,
                            Title = "Refined Granite Bike"
                        },
                        new
                        {
                            Id = 3,
                            Color = "teal",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImageUrl = "https://loremflickr.com/320/240?lock=735376770",
                            MaterialCategoryId = 1,
                            Premium = true,
                            Title = "Rustic Cotton Car"
                        },
                        new
                        {
                            Id = 4,
                            Color = "maroon",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImageUrl = "https://loremflickr.com/320/240?lock=939764289",
                            MaterialCategoryId = 5,
                            Premium = false,
                            Title = "Intelligent Rubber Table"
                        },
                        new
                        {
                            Id = 5,
                            Color = "white",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ImageUrl = "https://loremflickr.com/320/240?lock=736454900",
                            MaterialCategoryId = 2,
                            Premium = false,
                            Title = "Unbranded Wooden Soap"
                        },
                        new
                        {
                            Id = 6,
                            Color = "magenta",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1475484605",
                            MaterialCategoryId = 3,
                            Premium = false,
                            Title = "Incredible Wooden Table"
                        },
                        new
                        {
                            Id = 7,
                            Color = "cyan",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1080277382",
                            MaterialCategoryId = 4,
                            Premium = true,
                            Title = "Licensed Fresh Table"
                        },
                        new
                        {
                            Id = 8,
                            Color = "turquoise",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImageUrl = "https://loremflickr.com/320/240?lock=513414332",
                            MaterialCategoryId = 1,
                            Premium = true,
                            Title = "Incredible Fresh Tuna"
                        },
                        new
                        {
                            Id = 9,
                            Color = "azure",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1620794650",
                            MaterialCategoryId = 1,
                            Premium = true,
                            Title = "Generic Frozen Soap"
                        },
                        new
                        {
                            Id = 10,
                            Color = "teal",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImageUrl = "https://loremflickr.com/320/240?lock=945560122",
                            MaterialCategoryId = 3,
                            Premium = false,
                            Title = "Unbranded Soft Ball"
                        },
                        new
                        {
                            Id = 11,
                            Color = "azure",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1725577467",
                            MaterialCategoryId = 4,
                            Premium = false,
                            Title = "Unbranded Cotton Sausages"
                        },
                        new
                        {
                            Id = 12,
                            Color = "white",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1683637580",
                            MaterialCategoryId = 5,
                            Premium = true,
                            Title = "Unbranded Rubber Soap"
                        },
                        new
                        {
                            Id = 13,
                            Color = "yellow",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1608979742",
                            MaterialCategoryId = 1,
                            Premium = true,
                            Title = "Intelligent Fresh Shoes"
                        },
                        new
                        {
                            Id = 14,
                            Color = "orchid",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1541969988",
                            MaterialCategoryId = 2,
                            Premium = false,
                            Title = "Ergonomic Frozen Shoes"
                        },
                        new
                        {
                            Id = 15,
                            Color = "olive",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImageUrl = "https://loremflickr.com/320/240?lock=837234833",
                            MaterialCategoryId = 5,
                            Premium = true,
                            Title = "Unbranded Granite Fish"
                        },
                        new
                        {
                            Id = 16,
                            Color = "cyan",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImageUrl = "https://loremflickr.com/320/240?lock=2067995836",
                            MaterialCategoryId = 2,
                            Premium = false,
                            Title = "Awesome Cotton Gloves"
                        },
                        new
                        {
                            Id = 17,
                            Color = "cyan",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1254714705",
                            MaterialCategoryId = 5,
                            Premium = false,
                            Title = "Generic Cotton Ball"
                        },
                        new
                        {
                            Id = 18,
                            Color = "orchid",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImageUrl = "https://loremflickr.com/320/240?lock=2104809561",
                            MaterialCategoryId = 4,
                            Premium = true,
                            Title = "Handcrafted Metal Sausages"
                        },
                        new
                        {
                            Id = 19,
                            Color = "turquoise",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1247655773",
                            MaterialCategoryId = 2,
                            Premium = true,
                            Title = "Incredible Plastic Tuna"
                        },
                        new
                        {
                            Id = 20,
                            Color = "purple",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImageUrl = "https://loremflickr.com/320/240?lock=784092226",
                            MaterialCategoryId = 1,
                            Premium = true,
                            Title = "Refined Wooden Cheese"
                        },
                        new
                        {
                            Id = 21,
                            Color = "cyan",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImageUrl = "https://loremflickr.com/320/240?lock=318425052",
                            MaterialCategoryId = 5,
                            Premium = false,
                            Title = "Intelligent Rubber Salad"
                        },
                        new
                        {
                            Id = 22,
                            Color = "purple",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImageUrl = "https://loremflickr.com/320/240?lock=858642731",
                            MaterialCategoryId = 4,
                            Premium = false,
                            Title = "Intelligent Steel Bike"
                        },
                        new
                        {
                            Id = 23,
                            Color = "green",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImageUrl = "https://loremflickr.com/320/240?lock=2108990447",
                            MaterialCategoryId = 2,
                            Premium = true,
                            Title = "Gorgeous Metal Salad"
                        },
                        new
                        {
                            Id = 24,
                            Color = "turquoise",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImageUrl = "https://loremflickr.com/320/240?lock=807239797",
                            MaterialCategoryId = 3,
                            Premium = false,
                            Title = "Ergonomic Concrete Sausages"
                        },
                        new
                        {
                            Id = 25,
                            Color = "olive",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1029418429",
                            MaterialCategoryId = 3,
                            Premium = false,
                            Title = "Handmade Plastic Table"
                        },
                        new
                        {
                            Id = 26,
                            Color = "purple",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImageUrl = "https://loremflickr.com/320/240?lock=2134824864",
                            MaterialCategoryId = 1,
                            Premium = true,
                            Title = "Refined Plastic Pizza"
                        },
                        new
                        {
                            Id = 27,
                            Color = "green",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImageUrl = "https://loremflickr.com/320/240?lock=356476069",
                            MaterialCategoryId = 2,
                            Premium = false,
                            Title = "Tasty Concrete Bike"
                        },
                        new
                        {
                            Id = 28,
                            Color = "lime",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1016643874",
                            MaterialCategoryId = 5,
                            Premium = true,
                            Title = "Awesome Plastic Bacon"
                        },
                        new
                        {
                            Id = 29,
                            Color = "teal",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1971998236",
                            MaterialCategoryId = 1,
                            Premium = true,
                            Title = "Sleek Wooden Shoes"
                        },
                        new
                        {
                            Id = 30,
                            Color = "fuchsia",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ImageUrl = "https://loremflickr.com/320/240?lock=975929757",
                            MaterialCategoryId = 2,
                            Premium = true,
                            Title = "Tasty Concrete Towels"
                        });
                });

            modelBuilder.Entity("P05Sklep.Shared.ProductAdjective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductAdjectives");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Practical"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Unbranded"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Intelligent"
                        });
                });

            modelBuilder.Entity("P05Sklep.Shared.Product_ProductAdjective", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductAdjectiveId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("ProductId", "ProductAdjectiveId");

                    b.HasIndex("ProductAdjectiveId");

                    b.ToTable("Product_ProductAdjectives");

                    b.HasData(
                        new
                        {
                            ProductId = 30,
                            ProductAdjectiveId = 3,
                            Price = 650m
                        },
                        new
                        {
                            ProductId = 15,
                            ProductAdjectiveId = 1,
                            Price = 879m
                        },
                        new
                        {
                            ProductId = 7,
                            ProductAdjectiveId = 3,
                            Price = 953m
                        },
                        new
                        {
                            ProductId = 6,
                            ProductAdjectiveId = 2,
                            Price = 323m
                        },
                        new
                        {
                            ProductId = 7,
                            ProductAdjectiveId = 1,
                            Price = 245m
                        },
                        new
                        {
                            ProductId = 10,
                            ProductAdjectiveId = 1,
                            Price = 429m
                        },
                        new
                        {
                            ProductId = 3,
                            ProductAdjectiveId = 1,
                            Price = 314m
                        },
                        new
                        {
                            ProductId = 5,
                            ProductAdjectiveId = 1,
                            Price = 558m
                        },
                        new
                        {
                            ProductId = 13,
                            ProductAdjectiveId = 3,
                            Price = 102m
                        },
                        new
                        {
                            ProductId = 12,
                            ProductAdjectiveId = 2,
                            Price = 112m
                        },
                        new
                        {
                            ProductId = 17,
                            ProductAdjectiveId = 3,
                            Price = 593m
                        },
                        new
                        {
                            ProductId = 28,
                            ProductAdjectiveId = 3,
                            Price = 200m
                        },
                        new
                        {
                            ProductId = 24,
                            ProductAdjectiveId = 3,
                            Price = 537m
                        },
                        new
                        {
                            ProductId = 15,
                            ProductAdjectiveId = 2,
                            Price = 755m
                        },
                        new
                        {
                            ProductId = 21,
                            ProductAdjectiveId = 2,
                            Price = 670m
                        },
                        new
                        {
                            ProductId = 1,
                            ProductAdjectiveId = 3,
                            Price = 366m
                        },
                        new
                        {
                            ProductId = 22,
                            ProductAdjectiveId = 2,
                            Price = 727m
                        },
                        new
                        {
                            ProductId = 19,
                            ProductAdjectiveId = 2,
                            Price = 811m
                        },
                        new
                        {
                            ProductId = 2,
                            ProductAdjectiveId = 3,
                            Price = 671m
                        },
                        new
                        {
                            ProductId = 11,
                            ProductAdjectiveId = 2,
                            Price = 70m
                        },
                        new
                        {
                            ProductId = 3,
                            ProductAdjectiveId = 3,
                            Price = 404m
                        },
                        new
                        {
                            ProductId = 12,
                            ProductAdjectiveId = 3,
                            Price = 817m
                        },
                        new
                        {
                            ProductId = 23,
                            ProductAdjectiveId = 1,
                            Price = 170m
                        },
                        new
                        {
                            ProductId = 27,
                            ProductAdjectiveId = 1,
                            Price = 839m
                        },
                        new
                        {
                            ProductId = 9,
                            ProductAdjectiveId = 3,
                            Price = 465m
                        },
                        new
                        {
                            ProductId = 21,
                            ProductAdjectiveId = 3,
                            Price = 987m
                        },
                        new
                        {
                            ProductId = 26,
                            ProductAdjectiveId = 1,
                            Price = 787m
                        },
                        new
                        {
                            ProductId = 19,
                            ProductAdjectiveId = 1,
                            Price = 795m
                        },
                        new
                        {
                            ProductId = 29,
                            ProductAdjectiveId = 2,
                            Price = 154m
                        },
                        new
                        {
                            ProductId = 2,
                            ProductAdjectiveId = 2,
                            Price = 923m
                        },
                        new
                        {
                            ProductId = 5,
                            ProductAdjectiveId = 2,
                            Price = 516m
                        },
                        new
                        {
                            ProductId = 25,
                            ProductAdjectiveId = 3,
                            Price = 963m
                        },
                        new
                        {
                            ProductId = 19,
                            ProductAdjectiveId = 3,
                            Price = 669m
                        },
                        new
                        {
                            ProductId = 8,
                            ProductAdjectiveId = 2,
                            Price = 493m
                        },
                        new
                        {
                            ProductId = 8,
                            ProductAdjectiveId = 3,
                            Price = 911m
                        },
                        new
                        {
                            ProductId = 1,
                            ProductAdjectiveId = 2,
                            Price = 296m
                        },
                        new
                        {
                            ProductId = 11,
                            ProductAdjectiveId = 3,
                            Price = 399m
                        },
                        new
                        {
                            ProductId = 13,
                            ProductAdjectiveId = 2,
                            Price = 66m
                        },
                        new
                        {
                            ProductId = 29,
                            ProductAdjectiveId = 3,
                            Price = 474m
                        },
                        new
                        {
                            ProductId = 4,
                            ProductAdjectiveId = 3,
                            Price = 149m
                        },
                        new
                        {
                            ProductId = 10,
                            ProductAdjectiveId = 3,
                            Price = 768m
                        },
                        new
                        {
                            ProductId = 20,
                            ProductAdjectiveId = 1,
                            Price = 433m
                        });
                });

            modelBuilder.Entity("P05Sklep.Shared.Product", b =>
                {
                    b.HasOne("P05Sklep.Shared.MaterialCategory", "MaterialCategory")
                        .WithMany()
                        .HasForeignKey("MaterialCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialCategory");
                });

            modelBuilder.Entity("P05Sklep.Shared.Product_ProductAdjective", b =>
                {
                    b.HasOne("P05Sklep.Shared.ProductAdjective", "ProductAdjective")
                        .WithMany()
                        .HasForeignKey("ProductAdjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P05Sklep.Shared.Product", "Product")
                        .WithMany("Product_ProductAdjectives")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductAdjective");
                });

            modelBuilder.Entity("P05Sklep.Shared.Product", b =>
                {
                    b.Navigation("Product_ProductAdjectives");
                });
#pragma warning restore 612, 618
        }
    }
}
